
def configure(cfg):
    cfg.extension_startup_loads.append("seqan-startup.lisp")
    pass

def build(bld):
    bld.extensions_source_files.append(bld.path.find_node("seqan.cc"))
    start_dir = bld.path
    bld.install_files('${PREFIX}/lib/clasp/extensions/seqan-clasp/src/',
        start_dir.ant_glob('**/*.lisp'),
        cwd=start_dir, relative_trick=True)
    bld.install_files('${PREFIX}/lib/clasp/extensions/seqan-clasp/src/',
        start_dir.ant_glob('**/*.asd'),
        cwd=start_dir, relative_trick=True)
    bld.install_files('${PREFIX}/lib/clasp/extensions/seqan-clasp/src/',
        start_dir.ant_glob('**/*.cc'),
        cwd=start_dir, relative_trick=True)
    src = bld.path.find_node("seqan-startup.lisp")
    dest = bld.path.get_bld().parent.parent.parent.make_node('extension-startup-loads/seqan-startup.lisp')
    print("About to add seqan-startup.lisp to %s" % dest.abspath())
    bld(source=src, target=dest, rule='cp ${SRC} ${TGT}')
    bld.install_as('${PREFIX}/bin/extension-startup-loads/seqan-startup.lisp', 'seqan-startup.lisp')

