
def configure(cfg):
    cfg.extensions_startup_scripts.append("seqan-startup.lisp")
    pass

def build(bld):
    bld.extensions_source_files.append(bld.path.find_node("seqan.cc"))
    start_dir = bld.path
    bld.install_files('${PREFIX}/lib/clasp/extensions/seqan-clasp/src/',
        start_dir.ant_glob('**/*.lisp'),
        cwd=start_dir, relative_trick=True)
    bld.install_files('${PREFIX}/lib/clasp/extensions/seqan-clasp/src/',
        start_dir.ant_glob('**/*.asd'),
        cwd=start_dir, relative_trick=True)
    bld.install_files('${PREFIX}/lib/clasp/extensions/seqan-clasp/src/',
        start_dir.ant_glob('**/*.cc'),
        cwd=start_dir, relative_trick=True)
        
